name: Akropolis
authors: [ ZetaStormy, ItsLewizzz ]
version: ${version}
description: A modern Minecraft server hub core solution. Based on DeluxeHub by ItsLewizz.
api-version: 1.19
main: team.devblook.akropolis.AkropolisPlugin
loadbefore: [ Essentials ]
softdepend: [ PlaceholderAPI, HeadDatabase, Multiverse-Core ]
libraries:
  - com.github.cryptomorin:XSeries:9.1.0

permissions:
  akropolis.*:
    description: Gives access to all Akropolis permissions
    children:
      akropolis.command.*: true
      akropolis.bypass.*: true
      akropolis.alert.*: true
      akropolis.item.*: true
      akropolis.player.*: true
      akropolis.block.*: true
  akropolis.command.*:
    description: Gives access to all command permissions
    children:
      akropolis.command.help: true
      akropolis.command.reload: true
      akropolis.command.scoreboard: true
      akropolis.command.openmenu: true
      akropolis.command.holograms: true
      akropolis.command.gamemode: true
      akropolis.command.gamemode.others: true
      akropolis.command.clearchat: true
      akropolis.command.lockchat: true
      akropolis.command.fly: true
      akropolis.command.fly.others: true
      akropolis.command.setlobby: true
      akropolis.command.vanish: true
  akropolis.bypass.*:
    description: Gives access to all bypass permissions
    children:
      akropolis.bypass.antiswear: true
      akropolis.bypass.commands: true
      akropolis.bypass.lockchat: true
      akropolis.bypass.antiwdl: true
      akropolis.bypass.doublejump: false
  akropolis.alert.*:
    description: Gives access to all alert permissions
    children:
      akropolis.alert.antiswear: true
      akropolis.alert.antiwdl: true
  akropolis.item.*:
    description: Gives access to all item based permissions
    children:
      akropolis.item.drop: true
      akropolis.item.pickup: true
  akropolis.player.*:
    description: Gives access to all player based permissions
    children:
      akropolis.player.pvp: true
  akropolis.block.*:
    description: Gives access to all block based permissions
    children:
      akropolis.block.break: true
      akropolis.block.place: true
      akropolis.block.interact: true
