# This workflow will build a DeluxeHub with Gradle and execute a SonarCloud analysis.
# It will be compiled against Java 8, 11 and 17.
name: Build and analyze DeluxeHub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on recommended JDK versions and execute analysis
    runs-on: ubuntu-latest

    # For Minecraft 1.8 - 1.12, Java 8 is recommended.
    # For Minecraft 1.13 - 1.16, Java 8 can be used but Java 11 is recommended.
    # For Minecraft 1.17 - 1.18, Java 17 is recommended/needed.
    strategy:
      matrix:
        java_version: [ 8, 11, 17 ]

    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis.

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Cleanup old JARs
        run: rm -f build/libs/*.jar

      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java_version }}
          distribution: temurin
          cache: gradle

      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any.
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew shadowJar sonarqube --info

      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: DeluxeHub Artifact
          path: build/libs/*.jar
