# This workflow will build a DeluxeHub with Maven.
# It will be compiled against Java 8, 11 and 16.
name: Build DeluxeHub

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build on recommended JDK versions
    runs-on: ubuntu-latest
    
    # For Minecraft 1.8 - 1.12, Java 8 is recommended.
    # For Minecraft 1.13 - 1.16, Java 8 can be used but Java 11 is recommended.
    # And for Minecraft 1.17, Java 16 is needed.
    strategy:
      matrix:
        java_version: [8, 11, 16]

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v2.3.4
    
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v2.1.0
      with:
        java-version: ${{ matrix.java_version }}
        distribution: 'adopt'
    
    - name: Cache Maven packages
      uses: actions/cache@v2.1.6
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2.2.3
      with:
        name: DeluxeHub Artifact
        path: target/*.jar
